# Site settings
title: Daniel Woo (Kyungjei Woo)
email: spikyedge@gmail.com 
description: >this is personal blog.
  I do not know about the dirrection of this blog yet.
  So I will trying to write everything that I have interested in.
  For example, movies, animations, books, medical things, and family. 
  
  # this means to ignore newlines until "baseurl:"
  
baseurl:  # the subpath of your site, e.g. /blog/
url: "http://www.kjwoo.com" # the base hostname & protocol for your site
twitter_username: https://twitter.com/os_kjwoo
github_username:  https://github.com/wookj

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Othropedic Surgeon / code poet"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""