# Site settings
title: "Daniel Woo (Kyungjei Woo)"
email: "spikyedge@gmail.com" 
description: > # this means to ignore newlines until "baseurl:"
  this is personal blog.
  I don't know about the dirrection of this blog yet.
  So I will trying to write everything that I have interested in.
  For example, movies, animations, books, medical things, and family.
  
baseurl: "http://www.kjwoo.com" # the subpath of your site, e.g. /blog/
url: "http://www.kjwoo.com" # the base hostname & protocol for your site
twitter_username: "@os_kjwoo"
github_username:  "wookj"

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Othropedic Surgeon / code poet"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""